spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/
      database: userdb
    redis:
      host: localhost
      port: 6379

  application:
    name: RedisJPA
  cache:
    type: redis

management:
  endpoints:
    web:
      exposure:
        include: "*"